import pandas as pd

ehi_data = [
    {
        "field_name": "ehi_schreiben",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "1. Schreiben",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zeichnen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "2. Zeichnen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_werfen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "3. Werfen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_schere",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "4. Schere",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zahnbuerste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "5. Zahnbürste",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_messer",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "6. Messer (ohne Gabel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_loeffel",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "7. Löffel",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_besen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "8. Besen (obere Hand)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_streichholz",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "9. Streichholz anzünden (Streichholz)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_kiste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "10. Öffnen einer Kiste (Deckel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
]
ehi = pd.DataFrame(ehi_data)
