import pandas as pd

fal_data = [
    {
        "field_name": "record_id",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Probanden-ID",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_datum",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Datum",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "date_ymd",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alter",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "1. Wie alt sind Sie? (Jahre)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "120",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_haendigkeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "2. Sind Sie",
        "choices": "1, rechtshändig | 2, linkshändig | 3, beidhändig",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_geschlecht",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "3. Geschlecht",
        "choices": "1, männlich | 2, weiblich | 3, anderes",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schulabschluss",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "4. Welchen Schulabschluss haben Sie?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_taetigkeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "5. Welcher Tätigkeit gehen Sie z.Zt. nach?",
        "choices": "1, Studium | 2, berufstätig | 3, nicht berufstätig",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studium_fachrichtung",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Fachrichtung (falls Studium)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_taetigkeit]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_beruf",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Beruf (falls berufstätig)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_taetigkeit]='2'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schlafdauer",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Wie viele Stunden haben Sie letzte Nacht geschlafen? (Stunden)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "24",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schlafdauer_bewertung",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "7. Diese Schlafdauer war für mich",
        "choices": "1, normal | 2, eher lang | 3, viel zu kurz, ich bin ziemlich müde",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alkohol",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "8. Haben Sie gestern Alkohol getrunken?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alkohol_menge",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte Menge angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_alkohol]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_raucher",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "9. Falls Sie Raucher sind: Haben Sie heute",
        "choices": "1, sehr viel | 2, normal | 3, wenig / gar nicht geraucht",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_koffein",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "10. Falls Sie Kaffee, Tee oder Cola trinken: Haben Sie heute",
        "choices": "1, sehr viel | 2, normal | 3, wenig/keine koffeinhaltigen Getränke getrunken",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_letzte_mahlzeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "11. Vor wie vielen Stunden haben Sie zum letzten Mal gegessen?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "48",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "12. Sind Sie z.Zt. in neurologischer, psychiatrischer oder psychologischer Behandlung?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_neuro]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_frueher",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "13. Waren Sie bereits früher einmal in neurologischer, psychiatrischer oder psychologischer Behandlung?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_frueher_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_neuro_frueher]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_aerztlich",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "14. Sind Sie z.Zt. in ärztlicher Behandlung (außer beim Neurologen/ Psychiater)?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_aerztlich_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_aerztlich]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_medikamente",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "15. Nehmen Sie z.Zt. Medikamente ein?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_medikamente_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_medikamente]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_drogen",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "16. Nehmen Sie Drogen oder haben Sie schon mal regelmäßig Drogen genommen?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_drogen_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_drogen]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studien_mv",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "17. Haben Sie bereits an Studien zur Bewegungsvorstellung teilgenommen?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studien_mv_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_studien_mv]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_mv_technik",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "18. Haben Sie bereits Bewegungsvorstellungstechniken genutzt, um eine Tätigkeit zu erlernen oder zu verbessern? (Sport, Instrumente o.ä.)",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_mv_technik_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_mv_technik]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_instrument",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "19. Spielen Sie ein Instrument? Wenn ja, welches? Wie lange schon? Wie oft spielen Sie in der Woche?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_sport",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "20. Treiben Sie regelmäßig Sport? Wenn ja, welche Sportarten? Wie lange schon? Wie oft betreibst Du diesen Sport in der Woche? (Bei Mehrfachantworten alles gesondert notieren!)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
]

fal = pd.DataFrame(fal_data)