import pandas as pd

ehi_data = [
    {
        "field_name": "ehi_schreiben",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "1. Schreiben",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zeichnen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "2. Zeichnen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_werfen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "3. Werfen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_schere",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "4. Schere",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zahnbuerste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "5. Zahnbürste",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_messer",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "6. Messer (ohne Gabel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_loeffel",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "7. Löffel",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_besen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "8. Besen (obere Hand)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_streichholz",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "9. Streichholz anzünden (Streichholz)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_kiste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "10. Öffnen einer Kiste (Deckel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
]
ehi = pd.DataFrame(ehi_data)

fal = pd.DataFrame([
    {"field_name": "record_id", "form_name": "fal", "field_type": "text", "field_label": "Probanden-ID", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_datum", "form_name": "fal", "field_type": "text", "field_label": "Datum", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "date_ymd", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_alter", "form_name": "fal", "field_type": "text", "field_label": "1. Wie alt sind Sie? (Jahre)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "integer", "text_validation_min": "0", "text_validation_max": "120", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_haendigkeit", "form_name": "fal", "field_type": "radio", "field_label": "2. Sind Sie", "choices": "1, rechtshändig | 2, linkshändig | 3, beidhändig", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_geschlecht", "form_name": "fal", "field_type": "radio", "field_label": "3. Geschlecht", "choices": "1, männlich | 2, weiblich | 3, anderes", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_schulabschluss", "form_name": "fal", "field_type": "text", "field_label": "4. Welchen Schulabschluss haben Sie?", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_taetigkeit", "form_name": "fal", "field_type": "radio", "field_label": "5. Welcher Tätigkeit gehen Sie z.Zt. nach?", "choices": "1, Studium | 2, berufstätig | 3, nicht berufstätig", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_studium_fachrichtung", "form_name": "fal", "field_type": "text", "field_label": "Fachrichtung (falls Studium)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_taetigkeit]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_beruf", "form_name": "fal", "field_type": "text", "field_label": "Beruf (falls berufstätig)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_taetigkeit]='2'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_schlafstunden", "form_name": "fal", "field_type": "text", "field_label": "6. Wie viele Stunden haben Sie letzte Nacht geschlafen?", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "integer", "text_validation_min": "0", "text_validation_max": "24", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_schlafdauer_empfinden", "form_name": "fal", "field_type": "radio", "field_label": "7. Diese Schlafdauer war für mich", "choices": "1, normal | 2, eher lang | 3, viel zu kurz, ich bin ziemlich müde", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_alkohol", "form_name": "fal", "field_type": "radio", "field_label": "8. Haben Sie gestern Alkohol getrunken?", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_alkohol_menge", "form_name": "fal", "field_type": "text", "field_label": "Menge Alkohol (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_alkohol]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_raucher", "form_name": "fal", "field_type": "radio", "field_label": "9. Falls Sie Raucher sind: Haben Sie heute", "choices": "1, sehr viel | 2, normal | 3, wenig / gar nicht", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_koffein", "form_name": "fal", "field_type": "radio", "field_label": "10. Falls Sie Kaffee, Tee oder Cola trinken: Haben Sie heute", "choices": "1, sehr viel | 2, normal | 3, wenig/keine koffeinhaltigen Getränke", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_letzte_mahlzeit", "form_name": "fal", "field_type": "text", "field_label": "11. Vor wie vielen Stunden haben Sie zum letzten Mal gegessen?", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "integer", "text_validation_min": "0", "text_validation_max": "48", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_neuro_behandlung", "form_name": "fal", "field_type": "radio", "field_label": "12. Sind Sie z.Zt. in neurologischer, psychiatrischer oder psychologischer Behandlung?", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_neuro_behandlung_grund", "form_name": "fal", "field_type": "text", "field_label": "Grund (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_neuro_behandlung]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_fruehere_neuro_behandlung", "form_name": "fal", "field_type": "radio", "field_label": "13. Waren Sie bereits früher einmal in neurologischer, psychiatrischer oder psychologischer Behandlung?", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_fruehere_neuro_behandlung_grund", "form_name": "fal", "field_type": "text", "field_label": "Grund (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_fruehere_neuro_behandlung]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_aerztliche_behandlung", "form_name": "fal", "field_type": "radio", "field_label": "14. Sind Sie z.Zt. in ärztlicher Behandlung (außer beim Neurologen/ Psychiater)?", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_aerztliche_behandlung_grund", "form_name": "fal", "field_type": "text", "field_label": "Grund (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_aerztliche_behandlung]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_medikamente", "form_name": "fal", "field_type": "radio", "field_label": "Nehmen Sie z.Zt. Medikamente ein?", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_medikamente_grund", "form_name": "fal", "field_type": "text", "field_label": "Welche Medikamente? (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_medikamente]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_drogen", "form_name": "fal", "field_type": "radio", "field_label": "16. Nehmen Sie Drogen oder haben Sie schon mal regelmäßig Drogen genommen?", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_drogen_grund", "form_name": "fal", "field_type": "text", "field_label": "Welche Drogen? (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_drogen]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_studien_bewegungsvorstellung", "form_name": "fal", "field_type": "radio", "field_label": "17. Haben Sie bereits an Studien zur Bewegungsvorstellung teilgenommen?", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_studien_bewegungsvorstellung_grund", "form_name": "fal", "field_type": "text", "field_label": "Welche Studien? (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_studien_bewegungsvorstellung]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_bewegungsvorstellungstechniken", "form_name": "fal", "field_type": "radio", "field_label": "18. Haben Sie bereits Bewegungsvorstellungstechniken genutzt, um eine Tätigkeit zu erlernen oder zu verbessern? (Sport, Instrumente o.ä.)", "choices": "0, Nein | 1, Ja", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_bewegungsvorstellungstechniken_grund", "form_name": "fal", "field_type": "text", "field_label": "Welche Tätigkeit? (falls Ja)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "[fal_bewegungsvorstellungstechniken]='1'", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_instrument", "form_name": "fal", "field_type": "note", "field_label": "19. Spielen Sie ein Instrument? Wenn ja, welches? Wie lange schon? Wie oft spielen Sie in der Woche?", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""},
    {"field_name": "fal_sport", "form_name": "fal", "field_type": "note", "field_label": "20. Treiben Sie regelmäßig Sport? Wenn ja, welche Sportarten? Wie lange schon? Wie oft betreibst Du diesen Sport in der Woche? (Bei Mehrfachantworten alles gesondert notieren!)", "choices": "", "field_note": "", "section_header": "", "text_validation_type_or_show_slider_number": "", "text_validation_min": "", "text_validation_max": "", "identifier": "", "branching_logic": "", "required_field": "", "custom_alignment": "", "question_number": "", "matrix_group_name": "", "matrix_ranking": "", "field_annotation": ""}
])